
export interface Recipe {
  rawId: string;
  enchantedId: string;
  amount: number;
  collectionCategory: string;
  collectionLevel: number;
  npcPrice?: number;
}

export const ROMAN_MAP: Record<number, string> = {
  1: 'I', 2: 'II', 3: 'III', 4: 'IV', 5: 'V', 6: 'VI', 7: 'VII', 8: 'VIII', 9: 'IX', 10: 'X'
};

export const RECIPES: Recipe[] = [
  { rawId: 'MELON', enchantedId: 'ENCHANTED_MELON', amount: 160, collectionCategory: 'MELON', collectionLevel: 1, npcPrice: 320 },
  { rawId: 'WHEAT', enchantedId: 'ENCHANTED_BREAD', amount: 60, collectionCategory: 'WHEAT', collectionLevel: 2, npcPrice: 60 },
  { rawId: 'WHEAT', enchantedId: 'ENCHANTED_HAY_BALE', amount: 160 * 60, collectionCategory: 'WHEAT', collectionLevel: 4, npcPrice: 160 * 60 },
  { rawId: 'WHEAT', enchantedId: 'TIGHTLY_TIED_HAY_BALE', amount: 144 * 160 * 60, collectionCategory: 'WHEAT', collectionLevel: 9, npcPrice: 144 * 160 * 60 },
  { rawId: 'CARROT_ITEM', enchantedId: 'ENCHANTED_CARROT', amount: 160, collectionCategory: 'CARROT', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'POTATO_ITEM', enchantedId: 'ENCHANTED_POTATO', amount: 160, collectionCategory: 'POTATO', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'PUMPKIN', enchantedId: 'ENCHANTED_PUMPKIN', amount: 160, collectionCategory: 'PUMPKIN', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'SUGAR_CANE', enchantedId: 'ENCHANTED_SUGAR', amount: 160, collectionCategory: 'SUGAR_CANE', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'SUGAR_CANE', enchantedId: 'ENCHANTED_SUGAR_CANE', amount: 160 * 160, collectionCategory: 'SUGAR_CANE', collectionLevel: 8, npcPrice: 51200 },
  { rawId: 'CACTUS', enchantedId: 'ENCHANTED_CACTUS_GREEN', amount: 160, collectionCategory: 'CACTUS', collectionLevel: 2, npcPrice: 160 },
  { rawId: 'ROTTEN_FLESH', enchantedId: 'ENCHANTED_ROTTEN_FLESH', amount: 160, collectionCategory: 'ROTTEN_FLESH', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'BONE', enchantedId: 'ENCHANTED_BONE', amount: 160, collectionCategory: 'BONE', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'STRING', enchantedId: 'ENCHANTED_STRING', amount: 160, collectionCategory: 'STRING', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'SPIDER_EYE', enchantedId: 'ENCHANTED_SPIDER_EYE', amount: 160, collectionCategory: 'SPIDER_EYE', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'SULPHUR', enchantedId: 'ENCHANTED_GUNPOWDER', amount: 160, collectionCategory: 'GUNPOWDER', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'IRON_INGOT', enchantedId: 'ENCHANTED_IRON', amount: 160, collectionCategory: 'IRON', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'GOLD_INGOT', enchantedId: 'ENCHANTED_GOLD', amount: 160, collectionCategory: 'GOLD', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'COAL', enchantedId: 'ENCHANTED_COAL', amount: 160, collectionCategory: 'COAL', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'COBBLESTONE', enchantedId: 'ENCHANTED_COBBLESTONE', amount: 160, collectionCategory: 'COBBLESTONE', collectionLevel: 2, npcPrice: 160 },
  { rawId: 'DIAMOND', enchantedId: 'ENCHANTED_DIAMOND', amount: 160, collectionCategory: 'DIAMOND', collectionLevel: 2, npcPrice: 1280 },
  { rawId: 'EMERALD', enchantedId: 'ENCHANTED_EMERALD', amount: 160, collectionCategory: 'EMERALD', collectionLevel: 2, npcPrice: 960 },
  { rawId: 'REDSTONE', enchantedId: 'ENCHANTED_REDSTONE', amount: 160, collectionCategory: 'REDSTONE', collectionLevel: 2, npcPrice: 160 },
  { rawId: 'INK_SACK:4', enchantedId: 'ENCHANTED_LAPIS_LAZULI', amount: 160, collectionCategory: 'LAPIS_LAZULI', collectionLevel: 2, npcPrice: 160 },
  { rawId: 'QUARTZ', enchantedId: 'ENCHANTED_QUARTZ', amount: 160, collectionCategory: 'QUARTZ', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'OBSIDIAN', enchantedId: 'ENCHANTED_OBSIDIAN', amount: 160, collectionCategory: 'OBSIDIAN', collectionLevel: 2, npcPrice: 1920 },
  { rawId: 'GLOWSTONE_DUST', enchantedId: 'ENCHANTED_GLOWSTONE_DUST', amount: 160, collectionCategory: 'GLOWSTONE', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'GRAVEL', enchantedId: 'ENCHANTED_FLINT', amount: 160, collectionCategory: 'FLINT', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'ICE', enchantedId: 'ENCHANTED_ICE', amount: 160, collectionCategory: 'ICE', collectionLevel: 2, npcPrice: 80 },
  { rawId: 'NETHER_STALK', enchantedId: 'ENCHANTED_NETHER_STALK', amount: 160, collectionCategory: 'NETHER_WART', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'MAGMA_CREAM', enchantedId: 'ENCHANTED_MAGMA_CREAM', amount: 160, collectionCategory: 'MAGMA_CREAM', collectionLevel: 2, npcPrice: 1280 },
  { rawId: 'SLIME_BALL', enchantedId: 'ENCHANTED_SLIME_BALL', amount: 160, collectionCategory: 'SLIME', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'GHAST_TEAR', enchantedId: 'ENCHANTED_GHAST_TEAR', amount: 5, collectionCategory: 'GHAST_TEAR', collectionLevel: 2, npcPrice: 80 },
  { rawId: 'ENDER_PEARL', enchantedId: 'ENCHANTED_ENDER_PEARL', amount: 16, collectionCategory: 'ENDER_PEARL', collectionLevel: 2, npcPrice: 160 },
  { rawId: 'LOG', enchantedId: 'ENCHANTED_OAK_LOG', amount: 160, collectionCategory: 'OAK_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LOG:1', enchantedId: 'ENCHANTED_SPRUCE_LOG', amount: 160, collectionCategory: 'SPRUCE_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LOG:2', enchantedId: 'ENCHANTED_BIRCH_LOG', amount: 160, collectionCategory: 'BIRCH_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LOG_2:1', enchantedId: 'ENCHANTED_DARK_OAK_LOG', amount: 160, collectionCategory: 'DARK_OAK_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LOG_2', enchantedId: 'ENCHANTED_ACACIA_LOG', amount: 160, collectionCategory: 'ACACIA_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LOG:3', enchantedId: 'ENCHANTED_JUNGLE_LOG', amount: 160, collectionCategory: 'JUNGLE_LOG', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'MUTTON', enchantedId: 'ENCHANTED_MUTTON', amount: 160, collectionCategory: 'MUTTON', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'PORK', enchantedId: 'ENCHANTED_PORK', amount: 160, collectionCategory: 'PORKCHOP', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'RAW_BEEF', enchantedId: 'ENCHANTED_RAW_BEEF', amount: 160, collectionCategory: 'RAW_BEEF', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'RAW_CHICKEN', enchantedId: 'ENCHANTED_RAW_CHICKEN', amount: 160, collectionCategory: 'CHICKEN', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'RAW_FISH', enchantedId: 'ENCHANTED_RAW_FISH', amount: 160, collectionCategory: 'RAW_FISH', collectionLevel: 2, npcPrice: 960 },
  { rawId: 'RAW_FISH:1', enchantedId: 'ENCHANTED_RAW_SALMON', amount: 160, collectionCategory: 'SALMON', collectionLevel: 2, npcPrice: 1440 },
  { rawId: 'CLAY_BALL', enchantedId: 'ENCHANTED_CLAY_BALL', amount: 160, collectionCategory: 'CLAY', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'SNOW_BALL', enchantedId: 'ENCHANTED_SNOW_BLOCK', amount: 640, collectionCategory: 'SNOW', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'RABBIT', enchantedId: 'ENCHANTED_RABBIT', amount: 160, collectionCategory: 'RABBIT', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'RABBIT_HIDE', enchantedId: 'ENCHANTED_RABBIT_HIDE', amount: 160, collectionCategory: 'RABBIT_HIDE', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'RABBIT_FOOT', enchantedId: 'ENCHANTED_RABBIT_FOOT', amount: 160, collectionCategory: 'RABBIT_FOOT', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'PRISMARINE_SHARD', enchantedId: 'ENCHANTED_PRISMARINE_SHARD', amount: 160, collectionCategory: 'PRISMARINE_SHARD', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'PRISMARINE_CRYSTALS', enchantedId: 'ENCHANTED_PRISMARINE_CRYSTALS', amount: 160, collectionCategory: 'PRISMARINE_CRYSTALS', collectionLevel: 2, npcPrice: 800 },
  { rawId: 'MUSHROOM_COLLECTION', enchantedId: 'ENCHANTED_BROWN_MUSHROOM', amount: 160, collectionCategory: 'MUSHROOM', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'MUSHROOM_COLLECTION', enchantedId: 'ENCHANTED_RED_MUSHROOM', amount: 160, collectionCategory: 'MUSHROOM', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'INK_SACK', enchantedId: 'ENCHANTED_INK_SACK', amount: 160, collectionCategory: 'INK_SACK', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'SAND', enchantedId: 'ENCHANTED_SAND', amount: 160, collectionCategory: 'SAND', collectionLevel: 2, npcPrice: 320 },
  { rawId: 'LEATHER', enchantedId: 'ENCHANTED_LEATHER', amount: 160, collectionCategory: 'LEATHER', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'FEATHER', enchantedId: 'ENCHANTED_FEATHER', amount: 160, collectionCategory: 'FEATHER', collectionLevel: 2, npcPrice: 480 },
  { rawId: 'PUFFERFISH', enchantedId: 'ENCHANTED_PUFFERFISH', amount: 160, collectionCategory: 'PUFFERFISH', collectionLevel: 2, npcPrice: 640 },
  { rawId: 'DIAMOND', enchantedId: 'ENCHANTED_DIAMOND_BLOCK', amount: 160 * 160, collectionCategory: 'DIAMOND', collectionLevel: 6, npcPrice: 1280 * 160 },
  { rawId: 'GOLD_INGOT', enchantedId: 'ENCHANTED_GOLD_BLOCK', amount: 160 * 160, collectionCategory: 'GOLD', collectionLevel: 6, npcPrice: 640 * 160 },
  { rawId: 'IRON_INGOT', enchantedId: 'ENCHANTED_IRON_BLOCK', amount: 160 * 160, collectionCategory: 'IRON', collectionLevel: 6, npcPrice: 480 * 160 },
  { rawId: 'EMERALD', enchantedId: 'ENCHANTED_EMERALD_BLOCK', amount: 160 * 160, collectionCategory: 'EMERALD', collectionLevel: 6, npcPrice: 960 * 160 },
  { rawId: 'INK_SACK:4', enchantedId: 'ENCHANTED_LAPIS_LAZULI_BLOCK', amount: 160 * 160, collectionCategory: 'LAPIS_LAZULI', collectionLevel: 6, npcPrice: 160 * 160 },
  { rawId: 'REDSTONE', enchantedId: 'ENCHANTED_REDSTONE_BLOCK', amount: 160 * 160, collectionCategory: 'REDSTONE', collectionLevel: 6, npcPrice: 160 * 160 },
  { rawId: 'COAL', enchantedId: 'ENCHANTED_COAL_BLOCK', amount: 160 * 160, collectionCategory: 'COAL', collectionLevel: 6, npcPrice: 320 * 160 },
  { rawId: 'QUARTZ', enchantedId: 'ENCHANTED_QUARTZ_BLOCK', amount: 160 * 160, collectionCategory: 'QUARTZ', collectionLevel: 6, npcPrice: 640 * 160 },
  { rawId: 'MELON', enchantedId: 'ENCHANTED_MELON_BLOCK', amount: 160 * 160, collectionCategory: 'MELON', collectionLevel: 6, npcPrice: 320 * 160 },
  { rawId: 'PUMPKIN', enchantedId: 'POLISHED_PUMPKIN', amount: 160 * 160, collectionCategory: 'PUMPKIN', collectionLevel: 6, npcPrice: 640 * 160 },
  { rawId: 'MUTTON', enchantedId: 'ENCHANTED_COOKED_MUTTON', amount: 160 * 160, collectionCategory: 'MUTTON', collectionLevel: 6, npcPrice: 800 * 160 },
  { rawId: 'PORK', enchantedId: 'ENCHANTED_GRILLED_PORK', amount: 160 * 160, collectionCategory: 'PORKCHOP', collectionLevel: 6, npcPrice: 800 * 160 },
  { rawId: 'RAW_FISH', enchantedId: 'ENCHANTED_COOKED_FISH', amount: 160 * 160, collectionCategory: 'RAW_FISH', collectionLevel: 6, npcPrice: 960 * 160 },
  { rawId: 'RAW_FISH:1', enchantedId: 'ENCHANTED_COOKED_SALMON', amount: 160 * 160, collectionCategory: 'SALMON', collectionLevel: 6, npcPrice: 1440 * 160 },
];

export const NAMES: Record<string, { en: string; zh: string }> = {
  'MELON': { en: 'Melon', zh: '西瓜' },
  'ENCHANTED_MELON': { en: 'Enchanted Melon', zh: '附魔西瓜' },
  'WHEAT': { en: 'Wheat', zh: '小麦' },
  'ENCHANTED_BREAD': { en: 'Enchanted Bread', zh: '附魔面包' },
  'ENCHANTED_HAY_BALE': { en: 'Enchanted Hay Bale', zh: '附魔干草块' },
  'TIGHTLY_TIED_HAY_BALE': { en: 'Tightly-Tied Hay Bale', zh: '紧实甘草卷' },
  'CARROT_ITEM': { en: 'Carrot', zh: '胡萝卜' },
  'ENCHANTED_CARROT': { en: 'Enchanted Carrot', zh: '附魔胡萝卜' },
  'POTATO_ITEM': { en: 'Potato', zh: '土豆' },
  'ENCHANTED_POTATO': { en: 'Enchanted Potato', zh: '附魔土豆' },
  'PUMPKIN': { en: 'Pumpkin', zh: '南瓜' },
  'ENCHANTED_PUMPKIN': { en: 'Enchanted Pumpkin', zh: '附魔南瓜' },
  'SUGAR_CANE': { en: 'Sugar Cane', zh: '甘蔗' },
  'ENCHANTED_SUGAR': { en: 'Enchanted Sugar', zh: '附魔糖' },
  'ENCHANTED_SUGAR_CANE': { en: 'Enchanted Sugar Cane', zh: '附魔甘蔗' },
  'CACTUS': { en: 'Cactus', zh: '仙人掌' },
  'ENCHANTED_CACTUS_GREEN': { en: 'Enchanted Cactus Green', zh: '附魔仙人掌绿' },
  'ROTTEN_FLESH': { en: 'Rotten Flesh', zh: '腐肉' },
  'ENCHANTED_ROTTEN_FLESH': { en: 'Enchanted Rotten Flesh', zh: '附魔腐肉' },
  'BONE': { en: 'Bone', zh: '骨头' },
  'ENCHANTED_BONE': { en: 'Enchanted Bone', zh: '附魔骨头' },
  'STRING': { en: 'String', zh: '线' },
  'ENCHANTED_STRING': { en: 'Enchanted String', zh: '附魔线' },
  'SPIDER_EYE': { en: 'Spider Eye', zh: '蜘蛛眼' },
  'ENCHANTED_SPIDER_EYE': { en: 'Enchanted Spider Eye', zh: '附魔蜘蛛眼' },
  'SULPHUR': { en: 'Gunpowder', zh: '火药' },
  'ENCHANTED_GUNPOWDER': { en: 'Enchanted Gunpowder', zh: '附魔火药' },
  'IRON_INGOT': { en: 'Iron Ingot', zh: '铁锭' },
  'ENCHANTED_IRON': { en: 'Enchanted Iron', zh: '附魔铁' },
  'GOLD_INGOT': { en: 'Gold Ingot', zh: '金锭' },
  'ENCHANTED_GOLD': { en: 'Enchanted Gold', zh: '附魔金' },
  'COAL': { en: 'Coal', zh: '煤炭' },
  'ENCHANTED_COAL': { en: 'Enchanted Coal', zh: '附魔煤炭' },
  'COBBLESTONE': { en: 'Cobblestone', zh: '圆石' },
  'ENCHANTED_COBBLESTONE': { en: 'Enchanted Cobblestone', zh: '附魔圆石' },
  'DIAMOND': { en: 'Diamond', zh: '钻石' },
  'ENCHANTED_DIAMOND': { en: 'Enchanted Diamond', zh: '附魔钻石' },
  'EMERALD': { en: 'Emerald', zh: '绿宝石' },
  'ENCHANTED_EMERALD': { en: 'Enchanted Emerald', zh: '附魔绿宝石' },
  'REDSTONE': { en: 'Redstone', zh: '红石' },
  'ENCHANTED_REDSTONE': { en: 'Enchanted Redstone', zh: '附魔红石' },
  'INK_SACK:4': { en: 'Lapis Lazuli', zh: '青金石' },
  'ENCHANTED_LAPIS_LAZULI': { en: 'Enchanted Lapis Lazuli', zh: '附魔青金石' },
  'QUARTZ': { en: 'Quartz', zh: '石英' },
  'ENCHANTED_QUARTZ': { en: 'Enchanted Quartz', zh: '附魔石英' },
  'OBSIDIAN': { en: 'Obsidian', zh: '黑曜石' },
  'ENCHANTED_OBSIDIAN': { en: 'Enchanted Obsidian', zh: '附魔黑曜石' },
  'GLOWSTONE_DUST': { en: 'Glowstone Dust', zh: '萤石粉' },
  'ENCHANTED_GLOWSTONE_DUST': { en: 'Enchanted Glowstone Dust', zh: '附魔萤石粉' },
  'GRAVEL': { en: 'Gravel', zh: '碎石' },
  'ENCHANTED_FLINT': { en: 'Enchanted Flint', zh: '附魔燧石' },
  'ICE': { en: 'Ice', zh: '冰' },
  'ENCHANTED_ICE': { en: 'Enchanted Ice', zh: '附魔冰' },
  'NETHER_STALK': { en: 'Nether Wart', zh: '下界之星' },
  'ENCHANTED_NETHER_STALK': { en: 'Enchanted Nether Wart', zh: '附魔下界之星' },
  'MAGMA_CREAM': { en: 'Magma Cream', zh: '岩浆膏' },
  'ENCHANTED_MAGMA_CREAM': { en: 'Enchanted Magma Cream', zh: '附魔岩浆膏' },
  'SLIME_BALL': { en: 'Slime Ball', zh: '粘液球' },
  'ENCHANTED_SLIME_BALL': { en: 'Enchanted Slime Ball', zh: '附魔粘液球' },
  'GHAST_TEAR': { en: 'Ghast Tear', zh: '恶魂之泪' },
  'ENCHANTED_GHAST_TEAR': { en: 'Enchanted Ghast Tear', zh: '附魔恶魂之泪' },
  'ENDER_PEARL': { en: 'Ender Pearl', zh: '末影珍珠' },
  'ENCHANTED_ENDER_PEARL': { en: 'Enchanted Ender Pearl', zh: '附魔末影珍珠' },
  'LOG': { en: 'Oak Log', zh: '橡木' },
  'ENCHANTED_OAK_LOG': { en: 'Enchanted Oak Log', zh: '附魔橡木' },
  'LOG:1': { en: 'Spruce Log', zh: '云杉木' },
  'ENCHANTED_SPRUCE_LOG': { en: 'Enchanted Spruce Log', zh: '附魔云杉木' },
  'LOG:2': { en: 'Birch Log', zh: '白桦木' },
  'ENCHANTED_BIRCH_LOG': { en: 'Enchanted Birch Log', zh: '附魔白桦木' },
  'LOG_2:1': { en: 'Dark Oak Log', zh: '深色橡木' },
  'ENCHANTED_DARK_OAK_LOG': { en: 'Enchanted Dark Oak Log', zh: '附魔深色橡木' },
  'LOG_2': { en: 'Acacia Log', zh: '金合欢木' },
  'ENCHANTED_ACACIA_LOG': { en: 'Enchanted Acacia Log', zh: '附魔金合欢木' },
  'LOG:3': { en: 'Jungle Log', zh: '丛林木' },
  'ENCHANTED_JUNGLE_LOG': { en: 'Enchanted Jungle Log', zh: '附魔丛林木' },
  'MUTTON': { en: 'Mutton', zh: '羊肉' },
  'ENCHANTED_MUTTON': { en: 'Enchanted Mutton', zh: '附魔羊肉' },
  'PORK': { en: 'Pork', zh: '猪肉' },
  'ENCHANTED_PORK': { en: 'Enchanted Pork', zh: '附魔猪肉' },
  'RAW_BEEF': { en: 'Raw Beef', zh: '生牛肉' },
  'ENCHANTED_RAW_BEEF': { en: 'Enchanted Raw Beef', zh: '附魔生牛肉' },
  'RAW_CHICKEN': { en: 'Raw Chicken', zh: '生鸡肉' },
  'ENCHANTED_RAW_CHICKEN': { en: 'Enchanted Raw Chicken', zh: '附魔生鸡肉' },
  'RAW_FISH': { en: 'Raw Fish', zh: '生鱼' },
  'ENCHANTED_RAW_FISH': { en: 'Enchanted Raw Fish', zh: '附魔生鱼' },
  'RAW_FISH:1': { en: 'Raw Salmon', zh: '生三文鱼' },
  'ENCHANTED_RAW_SALMON': { en: 'Enchanted Raw Salmon', zh: '附魔生三文鱼' },
  'CLAY_BALL': { en: 'Clay', zh: '粘土' },
  'ENCHANTED_CLAY_BALL': { en: 'Enchanted Clay', zh: '附魔粘土' },
  'SNOW_BALL': { en: 'Snowball', zh: '雪球' },
  'ENCHANTED_SNOW_BLOCK': { en: 'Enchanted Snow Block', zh: '附魔雪块' },
  'RABBIT': { en: 'Rabbit', zh: '兔子' },
  'ENCHANTED_RABBIT': { en: 'Enchanted Rabbit', zh: '附魔兔子' },
  'RABBIT_HIDE': { en: 'Rabbit Hide', zh: '兔皮' },
  'ENCHANTED_RABBIT_HIDE': { en: 'Enchanted Rabbit Hide', zh: '附魔兔皮' },
  'RABBIT_FOOT': { en: 'Rabbit Foot', zh: '兔子脚' },
  'ENCHANTED_RABBIT_FOOT': { en: 'Enchanted Rabbit Foot', zh: '附魔兔子脚' },
  'PRISMARINE_SHARD': { en: 'Prismarine Shard', zh: '海晶石碎片' },
  'ENCHANTED_PRISMARINE_SHARD': { en: 'Enchanted Prismarine Shard', zh: '附魔海晶石碎片' },
  'PRISMARINE_CRYSTALS': { en: 'Prismarine Crystals', zh: '海晶石晶体' },
  'ENCHANTED_PRISMARINE_CRYSTALS': { en: 'Enchanted Prismarine Crystals', zh: '附魔海晶石晶体' },
  'MUSHROOM_COLLECTION': { en: 'Mushroom', zh: '蘑菇' },
  'ENCHANTED_BROWN_MUSHROOM': { en: 'Enchanted Brown Mushroom', zh: '附魔褐蘑菇' },
  'ENCHANTED_RED_MUSHROOM': { en: 'Enchanted Red Mushroom', zh: '附魔红蘑菇' },
  'INK_SACK': { en: 'Ink Sack', zh: '墨囊' },
  'ENCHANTED_INK_SACK': { en: 'Enchanted Ink Sack', zh: '附魔墨囊' },
  'SAND': { en: 'Sand', zh: '沙子' },
  'ENCHANTED_SAND': { en: 'Enchanted Sand', zh: '附魔沙子' },
  'LEATHER': { en: 'Leather', zh: '皮革' },
  'ENCHANTED_LEATHER': { en: 'Enchanted Leather', zh: '附魔皮革' },
  'FEATHER': { en: 'Feather', zh: '羽毛' },
  'ENCHANTED_FEATHER': { en: 'Enchanted Feather', zh: '附魔羽毛' },
  'PUFFERFISH': { en: 'Pufferfish', zh: '河豚' },
  'ENCHANTED_PUFFERFISH': { en: 'Enchanted Pufferfish', zh: '附魔河豚' },
  'ENCHANTED_DIAMOND_BLOCK': { en: 'Enchanted Diamond Block', zh: '附魔钻石块' },
  'ENCHANTED_GOLD_BLOCK': { en: 'Enchanted Gold Block', zh: '附魔金块' },
  'ENCHANTED_IRON_BLOCK': { en: 'Enchanted Iron Block', zh: '附魔铁块' },
  'ENCHANTED_EMERALD_BLOCK': { en: 'Enchanted Emerald Block', zh: '附魔绿宝石块' },
  'ENCHANTED_LAPIS_LAZULI_BLOCK': { en: 'Enchanted Lapis Block', zh: '附魔青金石块' },
  'ENCHANTED_REDSTONE_BLOCK': { en: 'Enchanted Redstone Block', zh: '附魔红石块' },
  'ENCHANTED_COAL_BLOCK': { en: 'Enchanted Coal Block', zh: '附魔煤炭块' },
  'ENCHANTED_QUARTZ_BLOCK': { en: 'Enchanted Quartz Block', zh: '附魔石英块' },
  'ENCHANTED_MELON_BLOCK': { en: 'Enchanted Melon Block', zh: '附魔西瓜块' },
  'POLISHED_PUMPKIN': { en: 'Polished Pumpkin', zh: '精制南瓜' },
  'ENCHANTED_COOKED_MUTTON': { en: 'Enchanted Cooked Mutton', zh: '附魔熟羊肉' },
  'ENCHANTED_GRILLED_PORK': { en: 'Enchanted Grilled Pork', zh: '附魔烤猪肉' },
  'ENCHANTED_COOKED_FISH': { en: 'Enchanted Cooked Fish', zh: '附魔熟鱼' },
  'ENCHANTED_COOKED_SALMON': { en: 'Enchanted Cooked Salmon', zh: '附魔熟三文鱼' },
};
